[theme]
base = "dark"
primaryColor = "#86B86B"
backgroundColor = "#101311"
secondaryBackgroundColor = "#191E1A"
textColor = "#EDF2EC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
